### ISSUE TITLE
phosphor-inventory: undefined symbol: _ZN9sdbusplus3xyz15openbmc_project9Inventory4Item6server4DimmC

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-inventory-manager#4]
I'm not sure what happened, but master is suddenly failing on witherspoon due to the following undefined symbol within inventory manager:

```
Jun 09 22:09:06 witherspoon-YL30UF74T02X phosphor-inventory[414]: phosphor-inventory: symbol lookup error: phosphor-inventory: undefined symbol: _ZN9sdbusplus3xyz15openbmc_project9Inventory4Item6server4DimmC1ERNS_3bus3busEPKcRKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt7variantIJSt6vectorISH_SaISH_EENS5_3EccENS5_10FormFactorESJ_ItSaItEEtbjyhSH_SJ_IjSaIjEENS5_10DeviceTypeEEESt4lessISH_ESaISt4pairIKSH_ST_EEEb
```

**Comment by geissonator** [comment]
Actually, master as of 2.9.0-dev-181-g2ef09ea51 is ok. So it's something in the meta-* queue that has caused this.

**Comment by bjwyman** [comment]
Was that fixed by this: https://github.com/openbmc/openbmc/commit/32654a436bd7904c10204251299a50cac55df0fb ?

**Comment by geissonator** [comment]
I think it may have been https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/34344. But either way, we're good to go now.
