### ISSUE TITLE
How to use an enum inside an initial inventory yaml file ?

### ISSUE THREAD

**Issue by frsauvage** [openbmc/phosphor-inventory-manager#7]
Hi,
I declared an enum in xxx.interface.yaml file.

=> I was not able to use it inside a yaml file, the once initially loaded. 

I tried:
<my.interface>:
  MyEnum:
    value: xyz.open_project.Inventory.MyClass.MyEnum.MyChoice
    type: xyz.open_project.Inventory.MyClass.MyEnum
  
or 
    type: enum[xyz.open_project.Inventory.MyClass.MyEnum]
or
    type: string

nothing compile => any idea ?

I would appreciate any help,
Best Regards,
Francine

**Comment by spinler** [comment]
Something like this?  https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-phosphor/inventory/inventory-cleanup/witherspoon/inventory-cleanup.yaml#L50

**Comment by frsauvage** [comment]
Thank a lot, @spinler, I missed it !
